In [23]:
import pandas as pd
import numpy as np

In [24]:
df =pd.read_csv('retail-orders-raw.csv')

In [25]:
df.shape

(12, 9)

In [26]:
df

,order_id,order_date,customer_segment,city,category,quantity,unit_price,discount_pct,payment_status
0,RT-1001,03-01-2026,Student,Chennai,Learning Kit,2,799,10.0,Paid
1,RT-1002,03-01-2026,Fresher,Bengaluru,Course Access,1,1499,0.0,paid
2,RT-1003,05-01-2026,student,Chennai,Course Access,1,1499,NaN,Pending
3,RT-1004,07-01-2026,Professional,Hyderabad,Learning Kit,3,799,5.0,Paid
4,RT-1004,07-01-2026,Professional,Hyderabad,Learning Kit,3,799,5.0,Paid
5,RT-1005,09-01-2026,Fresher,NaN,Mentor Session,1,999,0.0,Failed
6,RT-1006,2026-13-10,Student,Pune,Learning Kit,-1,799,10.0,Paid
7,RT-1007,12-01-2026,Professional,Mumbai,Mentor Session,2,999,105.0,Paid
8,RT-1008,14-01-2026,Fresher,Bengaluru,Course Access,two,1499,0.0,Pending
9,RT-1009,16-01-2026,Student,Chennai,Learning Kit,1,799,0.0,Paid
10,RT-1010,18-01-2026,Professional,Delhi,Course Access,2,1499,15.0,Refunded
11,RT-1011,NaN,Student,Kochi,Mentor Session,1,999,0.0,Paid

In [27]:

duplicate_count = df.duplicated().sum()
# print(f"Total duplicate rows: {duplicate_count}")

In [28]:
# Duplicate rows remove karein
df = df.drop_duplicates()
print("Duplicates hatane ke baad rows:", len(df))

Duplicates hatane ke baad rows: 11

In [29]:
df

,order_id,order_date,customer_segment,city,category,quantity,unit_price,discount_pct,payment_status
0,RT-1001,03-01-2026,Student,Chennai,Learning Kit,2,799,10.0,Paid
1,RT-1002,03-01-2026,Fresher,Bengaluru,Course Access,1,1499,0.0,paid
2,RT-1003,05-01-2026,student,Chennai,Course Access,1,1499,NaN,Pending
3,RT-1004,07-01-2026,Professional,Hyderabad,Learning Kit,3,799,5.0,Paid
5,RT-1005,09-01-2026,Fresher,NaN,Mentor Session,1,999,0.0,Failed
6,RT-1006,2026-13-10,Student,Pune,Learning Kit,-1,799,10.0,Paid
7,RT-1007,12-01-2026,Professional,Mumbai,Mentor Session,2,999,105.0,Paid
8,RT-1008,14-01-2026,Fresher,Bengaluru,Course Access,two,1499,0.0,Pending
9,RT-1009,16-01-2026,Student,Chennai,Learning Kit,1,799,0.0,Paid
10,RT-1010,18-01-2026,Professional,Delhi,Course Access,2,1499,15.0,Refunded
11,RT-1011,NaN,Student,Kochi,Mentor Session,1,999,0.0,Paid

In [30]:
df['order_date'] = df['order_date'].fillna('2026-01-01')

C:\Users\saura\AppData\Local\Temp\ipykernel_30048\2265145145.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['order_date'] = df['order_date'].fillna('2026-01-01')

In [31]:
df['customer_segment']=df['customer_segment'].str.strip().str.title()

C:\Users\saura\AppData\Local\Temp\ipykernel_30048\2811164889.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['customer_segment']=df['customer_segment'].str.strip().str.title()

In [32]:
df=df.reset_index(drop=True)

In [33]:
df

,order_id,order_date,customer_segment,city,category,quantity,unit_price,discount_pct,payment_status
0,RT-1001,03-01-2026,Student,Chennai,Learning Kit,2,799,10.0,Paid
1,RT-1002,03-01-2026,Fresher,Bengaluru,Course Access,1,1499,0.0,paid
2,RT-1003,05-01-2026,Student,Chennai,Course Access,1,1499,NaN,Pending
3,RT-1004,07-01-2026,Professional,Hyderabad,Learning Kit,3,799,5.0,Paid
4,RT-1005,09-01-2026,Fresher,NaN,Mentor Session,1,999,0.0,Failed
5,RT-1006,2026-13-10,Student,Pune,Learning Kit,-1,799,10.0,Paid
6,RT-1007,12-01-2026,Professional,Mumbai,Mentor Session,2,999,105.0,Paid
7,RT-1008,14-01-2026,Fresher,Bengaluru,Course Access,two,1499,0.0,Pending
8,RT-1009,16-01-2026,Student,Chennai,Learning Kit,1,799,0.0,Paid
9,RT-1010,18-01-2026,Professional,Delhi,Course Access,2,1499,15.0,Refunded
10,RT-1011,2026-01-01,Student,Kochi,Mentor Session,1,999,0.0,Paid

In [34]:
df['city']=df['city'].fillna('Unknown')

In [35]:
df

,order_id,order_date,customer_segment,city,category,quantity,unit_price,discount_pct,payment_status
0,RT-1001,03-01-2026,Student,Chennai,Learning Kit,2,799,10.0,Paid
1,RT-1002,03-01-2026,Fresher,Bengaluru,Course Access,1,1499,0.0,paid
2,RT-1003,05-01-2026,Student,Chennai,Course Access,1,1499,NaN,Pending
3,RT-1004,07-01-2026,Professional,Hyderabad,Learning Kit,3,799,5.0,Paid
4,RT-1005,09-01-2026,Fresher,Unknown,Mentor Session,1,999,0.0,Failed
5,RT-1006,2026-13-10,Student,Pune,Learning Kit,-1,799,10.0,Paid
6,RT-1007,12-01-2026,Professional,Mumbai,Mentor Session,2,999,105.0,Paid
7,RT-1008,14-01-2026,Fresher,Bengaluru,Course Access,two,1499,0.0,Pending
8,RT-1009,16-01-2026,Student,Chennai,Learning Kit,1,799,0.0,Paid
9,RT-1010,18-01-2026,Professional,Delhi,Course Access,2,1499,15.0,Refunded
10,RT-1011,2026-01-01,Student,Kochi,Mentor Session,1,999,0.0,Paid

In [36]:


df['order_date']=pd.to_datetime(df['order_date'], errors='coerce',format='mixed')

In [37]:
df.loc[6 ,'order_date']=pd.to_datetime('2026-01-12')

In [38]:
df

,order_id,order_date,customer_segment,city,category,quantity,unit_price,discount_pct,payment_status
0,RT-1001,2026-03-01,Student,Chennai,Learning Kit,2,799,10.0,Paid
1,RT-1002,2026-03-01,Fresher,Bengaluru,Course Access,1,1499,0.0,paid
2,RT-1003,2026-05-01,Student,Chennai,Course Access,1,1499,NaN,Pending
3,RT-1004,2026-07-01,Professional,Hyderabad,Learning Kit,3,799,5.0,Paid
4,RT-1005,2026-09-01,Fresher,Unknown,Mentor Session,1,999,0.0,Failed
5,RT-1006,NaT,Student,Pune,Learning Kit,-1,799,10.0,Paid
6,RT-1007,2026-01-12,Professional,Mumbai,Mentor Session,2,999,105.0,Paid
7,RT-1008,2026-01-14,Fresher,Bengaluru,Course Access,two,1499,0.0,Pending
8,RT-1009,2026-01-16,Student,Chennai,Learning Kit,1,799,0.0,Paid
9,RT-1010,2026-01-18,Professional,Delhi,Course Access,2,1499,15.0,Refunded
10,RT-1011,2026-01-01,Student,Kochi,Mentor Session,1,999,0.0,Paid

In [39]:
df.loc[5,'order_date']=pd.to_datetime('2026-10-13')

In [40]:
df['quantity']=df['quantity'].replace({'two':2, -1 : 1, '-1':1})

df['quantity'] = pd.to_numeric(df['quantity'])

In [41]:
df

,order_id,order_date,customer_segment,city,category,quantity,unit_price,discount_pct,payment_status
0,RT-1001,2026-03-01,Student,Chennai,Learning Kit,2,799,10.0,Paid
1,RT-1002,2026-03-01,Fresher,Bengaluru,Course Access,1,1499,0.0,paid
2,RT-1003,2026-05-01,Student,Chennai,Course Access,1,1499,NaN,Pending
3,RT-1004,2026-07-01,Professional,Hyderabad,Learning Kit,3,799,5.0,Paid
4,RT-1005,2026-09-01,Fresher,Unknown,Mentor Session,1,999,0.0,Failed
5,RT-1006,2026-10-13,Student,Pune,Learning Kit,1,799,10.0,Paid
6,RT-1007,2026-01-12,Professional,Mumbai,Mentor Session,2,999,105.0,Paid
7,RT-1008,2026-01-14,Fresher,Bengaluru,Course Access,2,1499,0.0,Pending
8,RT-1009,2026-01-16,Student,Chennai,Learning Kit,1,799,0.0,Paid
9,RT-1010,2026-01-18,Professional,Delhi,Course Access,2,1499,15.0,Refunded
10,RT-1011,2026-01-01,Student,Kochi,Mentor Session,1,999,0.0,Paid

In [42]:
df['discount_pct']=df['discount_pct'].fillna(0.0)

In [43]:
df['discount_pct']=df['discount_pct'].replace(105.0 , 10.5)

In [44]:
df

,order_id,order_date,customer_segment,city,category,quantity,unit_price,discount_pct,payment_status
0,RT-1001,2026-03-01,Student,Chennai,Learning Kit,2,799,10.0,Paid
1,RT-1002,2026-03-01,Fresher,Bengaluru,Course Access,1,1499,0.0,paid
2,RT-1003,2026-05-01,Student,Chennai,Course Access,1,1499,0.0,Pending
3,RT-1004,2026-07-01,Professional,Hyderabad,Learning Kit,3,799,5.0,Paid
4,RT-1005,2026-09-01,Fresher,Unknown,Mentor Session,1,999,0.0,Failed
5,RT-1006,2026-10-13,Student,Pune,Learning Kit,1,799,10.0,Paid
6,RT-1007,2026-01-12,Professional,Mumbai,Mentor Session,2,999,10.5,Paid
7,RT-1008,2026-01-14,Fresher,Bengaluru,Course Access,2,1499,0.0,Pending
8,RT-1009,2026-01-16,Student,Chennai,Learning Kit,1,799,0.0,Paid
9,RT-1010,2026-01-18,Professional,Delhi,Course Access,2,1499,15.0,Refunded
10,RT-1011,2026-01-01,Student,Kochi,Mentor Session,1,999,0.0,Paid

In [45]:
df['payment_status']=df['payment_status'].str.title()

In [46]:
df

,order_id,order_date,customer_segment,city,category,quantity,unit_price,discount_pct,payment_status
0,RT-1001,2026-03-01,Student,Chennai,Learning Kit,2,799,10.0,Paid
1,RT-1002,2026-03-01,Fresher,Bengaluru,Course Access,1,1499,0.0,Paid
2,RT-1003,2026-05-01,Student,Chennai,Course Access,1,1499,0.0,Pending
3,RT-1004,2026-07-01,Professional,Hyderabad,Learning Kit,3,799,5.0,Paid
4,RT-1005,2026-09-01,Fresher,Unknown,Mentor Session,1,999,0.0,Failed
5,RT-1006,2026-10-13,Student,Pune,Learning Kit,1,799,10.0,Paid
6,RT-1007,2026-01-12,Professional,Mumbai,Mentor Session,2,999,10.5,Paid
7,RT-1008,2026-01-14,Fresher,Bengaluru,Course Access,2,1499,0.0,Pending
8,RT-1009,2026-01-16,Student,Chennai,Learning Kit,1,799,0.0,Paid
9,RT-1010,2026-01-18,Professional,Delhi,Course Access,2,1499,15.0,Refunded
10,RT-1011,2026-01-01,Student,Kochi,Mentor Session,1,999,0.0,Paid

In [52]:
total_quantity = df['quantity'].sum()
print(f"1. Total quantity: {total_quantity}")

1. Total quantity: 17

In [53]:
total_revenue = df['unit_price'].sum()
print(f"2. Total Revenue: ₹{total_revenue:.2f}")

2. Total Revenue: ₹12189.00

In [54]:
total_orders = df['order_id'].nunique()
print(f"3.  Total Orders  : {total_orders}")

3.  Total Orders  : 11

In [57]:
paid_pct = (df['payment_status'] == 'Paid').mean() * 100
print(f"4. Successful Payment Rate : {paid_pct:.2f}%")

4. Successful Payment Rate : 63.64%

In [58]:
avg_discount = df['discount_pct'].mean()
print(f"5. Average Discount Percentage  : {avg_discount:.2f}%")

5. Average Discount Percentage  : 4.59%

In [60]:
average_price = df['unit_price'].mean()

print(f"6. Average Unit Price: ₹{average_price:.2f}")

6. Average Unit Price: ₹1108.09

In [61]:
top_city = df['city'].value_counts().idxmax()
print(f"7. Top City by Sales : {top_city}")

7. Top City by Sales : Chennai

In [66]:
for seg in df['customer_segment'].unique():
    # Har segment ka data filter karein
    sub_df = df[df['customer_segment'] == seg]
    
    seg_orders = sub_df['order_id'].count()
    seg_qty = sub_df['quantity'].sum()
    seg_revenue = sub_df['unit_price'].sum()
    
    print(f"   • Segment: {seg}")
    print(f"     - Orders   : {seg_orders}")
    print(f"     - Quantity : {seg_qty}")
    print(f"     - Revenue  : ₹{seg_revenue:.2f}\n")

   • Segment: Student
     - Orders   : 5
     - Quantity : 6
     - Revenue  : ₹4895.00

   • Segment: Fresher
     - Orders   : 3
     - Quantity : 4
     - Revenue  : ₹3997.00

   • Segment: Professional
     - Orders   : 3
     - Quantity : 7
     - Revenue  : ₹3297.00